open-api:
  naver:
    clientId: TlGy_NfWdes1o_olqEHW
    clientSecret: OLelLYEnbi
  kakao:
    restApi: 948a23f74ed9d2800a191d2d55846a84
    nativeApi: 211d8a55b6c980eb0ee11214255f921b
  publicPerformance:
    serverApi: 19g8EIV14ZGziVgAZacZ%2BRjN7%2BmE0KpRpl6Pf5Em2DpQ3lBJIBYIfAzjJrlg0C%2BZwNv6DmPii9WdqP0RgpAAPg%3D%3D
#     serverApi: jXdXc1GXAE0yd3d2HHUM8dy%2B126jZGEFWeXIb7zoZyPPYLTaM4csywE8P9PZFLbejXaA41AxjP3LDVjHudHrTw%3D%3D