open-api:
  naver:
    clientId: TlGy_NfWdes1o_olqEHW
    clientSecret: OLelLYEnbi
  kakao:
    restApi: 948a23f74ed9d2800a191d2d55846a84
    nativeApi: 211d8a55b6c980eb0ee11214255f921b
#    javascript-api: 386db79224235d8ec1522fdc1ac4b5a8
#    admin-api: d9f2580fe02b4f3f830c950787a35e9e

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/favoritecoffee
#    username: root
#    password: h1033489
#  jpa:
#    hibernate:
#      ddl-auto: create
#    